### ISSUE TITLE
Provide option to not hide local cursor

### ISSUE THREAD

**Issue by skt041959** [sipper69/Control3#10]
Hi Developer,

First of all, I must say I really enjoy work with Control3 and thank you for your quick support to fix my previous issue!

Here is a suggestion that, if you can provide an option to not hide local cursor, that will be a perfect ipkvm tool in my opinion!

The reason is that some USB capture which provide a higher resolution could cause to higher latency. A local cursor will help to smooth the mouse action. Currently I'm using the PowerToys to add a cross-marker at the cursor location, which is also a good solution for me.

Regards!

**Comment by sipper69** [comment]
Hi!

I understand. I found the two mouse pointers annoying and tried to change one to a red cross, but I believe WinUI3 did not cooperate :-)

But let me recheck that! At the very least, I can add a checkbox to "hide mouse pointer."

Let me see when I can find some time.

**Comment by sipper69** [comment]
Hi, 

I pushed a new version to the MS Store.
Usually takes up to  2/3 days to become available.

Let me know if this works for you!

Cheers

**Comment by skt041959** [comment]
Yes, great! The cross marker works perfectly! Thank you for the effort, can't believe it's a free software!
