### ISSUE TITLE
Source code does not match released Control3 version

### ISSUE THREAD

**Issue by bp2008** [sipper69/Control3#11]
Hi.

I tried building the app myself to figure out why there is so much mouse lag, and it turns out the source code in this git repository is very out-of-date compared to what you released on the Microsoft Store.

Do you think you could push the latest source code to git?

**Comment by sipper69** [comment]
Hi bp2008.

That version is closed. 
I did some redesign there indeed, see:
https://github.com/sipper69/Control3/discussions/2#discussioncomment-9028757

**Comment by sipper69** [comment]
Instead of sending all movements in parallel threads, I now only send the next movement when the ch9329 is ready, and send the delta between the last and current position (in case of relative, absolute is easy of course).

The ch9329 could simply not catch up with the high movement packet load.

Increasing the bitrate could probably be an option as well. But you need that Chinese tool to do that. Never tried that.

**Comment by bp2008** [comment]
It is strange to use github for a closed source program.  Do you mind saying why you have not made your improvements open source?  It is impossible for anyone to contribute improvements this way.

**Comment by sipper69** [comment]
That is a matter of interpretation.
But maybe you're right. 
When I find the time I'll decouple this GitHub contribution and the separate development.

**Comment by bp2008** [comment]
From what I can tell, the CH9329 adapter is adding most of the input latency and I think it is not a software bug, but probably just a limitation of the hardware.  If I plug in a mouse directly to the "remote" machine and just feed video through Control3 the input lag is very much improved.

I tried to use a higher baud rate for the CH9329 serial connection to see if it improves latency, but I have not been successful yet.  If I can make the [CH9329 Debugging tools](https://github.com/user-attachments/files/18067356/CH9329.Debugging.tools.zip) render their Chinese fonts correctly, I can use a translation app to figure out how it works maybe.

I am curious why you made all the later versions of Control3 be closed-source.  Can you share the reason?

**Comment by sipper69** [comment]
Baudrate should certainly help! Keep me posted. 

I made some screenshots earlier, looked okay. Did not use it though.

The further development is for a future project. No details yet, maybe I will publish the source code later. Time will tell.

**Comment by bp2008** [comment]
Changing the CH9329 baud rate does have a large effect on input latency.  As expected, increasing the baud rate reduces the input latency.  Lowering the baud rate increases the input latency, and at lower values like 2400 baud, the mouse position updates less frequently.  57600 seems to be best.  115200 makes it stutter a little bit and is not noticeably faster to me.

I tested with Control3 configured to use absolute mouse position and draw the local pointer as a cross, and dragged the mouse around on [this website](https://www.vsynctester.com/testing/mouse.html) which draws a red thing 2 frames behind your mouse pointer which is good for comparison purposes.  Based on that, at 57600 baud rate it seems to take about 1.5 frames (at 60hz) for mouse movement to be reflected in the remote view.  In other words about 25 milliseconds.  This is surprisingly good for hardware that is not optimized for bare minimum latency.

To change the baud rate I had to use the `CH9329Test_CfgTool` program from the link I posted earlier.  To read the text in the program to make sense of it, I had to set Chinese Simplified as my system's default language and also set it as default for non-unicode apps. 
 Then the text was able to render correctly and Google Translate/Lens could translate it via a phone camera.

![2024-12-09 19 15 02](https://github.com/user-attachments/assets/1de9a1ee-c363-4495-88be-5a65d4697468)

To change baud rate:

1. I plugged both ends of the cord into the same PC.
2. Open `CH9329Test_CfgTool` program.
3. Select the current baud rate in the dropdown at the top right.
4. Connect to the device via "Open serial port" button right of "Baud rate" dropdown.
5. Click "Get parameters" button.
6. Change "Serial port baud rate" field to desired value.
7. Click "Set parameters" button.
8. Click "Close serial port" 
9. Close program.
10. Unplug both ends of the cord.

Then change the baud rate setting in Control3 software and plug the cord back in.

FYI I notice Control3 can connect to the CH9329 device with the baud rate set slightly wrong (e.g. if you enter 36400 when real baud rate is 38400) and it causes glitchy mouse movement.  A good future improvement may be to change the baud rate input field to a dropdown list that matches the baud rates available in the CH9329 configuration tool.

**Comment by sipper69** [comment]
What a great work BP.

I'll do the same steps, I'm really curious about the performance improvement. The dropdown suggestion is noted. 

Thank you for your contribution!

**Comment by robinvanemden** [comment]
Just a quick FYI: I downloaded [these drivers](https://www.wch-ic.com/downloads/CH341SER_ZIP.html) for my ARM64 Windows 11 laptop, and they work perfectly with the Windows Store version of Control3. I also followed BP's instructions to set the baud rate to 57600, which works like a charm too.

**Comment by sipper69** [comment]
Nice! 

Btw, I'll release an update soon where you can program the Baudrate from within Control3 :-)
