### ISSUE TITLE
Screen Scaling results in almost unusable application window

### ISSUE THREAD

**Issue by Arbad-147** [sipper69/Control3#5]
I have an XPS with a 4k screen that I run at 200% scale...

What I get is a windows that is too small to display everything. I've tried setting the compatibility and it seems to make no difference.

![Control3 Window](https://github.com/sipper69/Control3/assets/140840111/b481965a-e0a8-41de-af6a-4f6fa5cec04a)

I know this is not a project that you have much time for but I'm wondering if you could take a look and see if it's something simple.

Thanks Very much

Thanks for sending those three cables

Kevin

**Comment by sipper69** [comment]
Hi Kevin. 

Never put any effort in scaling of the main window.
But I will now :-)

I'll find some time somewhere this month, will do that on the MS App Store version, not this repository though.
Seeing the screenshot, you don't have a problem with regular use (start a session) at the moment, right?

**Comment by Arbad-147** [comment]
I was able to make it work by clicking near what I think is there and it launches... I have used it a few times last week and it worked great. I didn't have to go get a monitor and carry that to the server room...

I'm arguing with it today, I got screen but no keyboard. I haven't started troubleshooting that yet. I think its a bad usb c to a adapter

**Comment by Arbad-147** [comment]
Oh, and thank you so much for this tool... and your help.

**Comment by sipper69** [comment]
You're welcome!

Please update through the Microsoft App store and you're scaling will be fixed ;-)

**Comment by Arbad-147** [comment]
Displays perfectly… Thank you very much.

 

I have a further question though and I want to be VERY CLEAR as to what I’m asking for…

 

I picked up 3 of the cables from you on Ebay and the first one I used has worked at first, but I found a couple of machines in a row that it would not work on… I used an external keyboard and then tested further when I got back to the office… It failed at first but after a replug and a wiggle it seemed fine… But then failed again onsite.

 

I tossed the second cable in my bag for use next time.

 

My question is: have you had any issues with these cables?

 

I’M NOT LOOKING FOR A REPLACEMENT… Just input. 

 

I think I found another source for the cable from AliExpress:

CH9329+CH340UART/TTL Serial Port to USB HID Full Keyboard and Mouse Drive-free Dual Male Module - AliExpress <https://www.aliexpress.com/item/1005006347644715.html> 

But I’m not sure what they mean by 1/5/20 control line

 

Thanks SO much for this tool, I have a pencil case with the cable and a USB A-C adapter, a hdmi cabe with a Capture adapter and a vga to hdmi adapter. Very convenient.

 

Kevin Miller

**Comment by sipper69** [comment]
Hi Kevin, 

I use a couple of cables frequently, never issues. 
But, having handled around 30 cables (test before send) one died on me as well. 
Cables are the same as you point out from Ali. 
They're no A-grade cables, but personally I'm very satisfied with price/quality.

I'm happy to hear Control3 is of use to you! 

Cheers
