### ISSUE TITLE
Datacenter use?

### ISSUE THREAD

**Issue by CodeMeZone** [sipper69/Control3#6]
This seems really cool, how well will this work with VGA? 

May I have some links, so I can get started? Thanks! 

US/china is ok.

**Comment by sipper69** [comment]
Interesting!

Well, Control3 should work with any video capture device. 

If you have a cable which captures your VGA and delivers it to your PC, you can use it. 

You can still use any low-budget HDMI capture device with a converter (VGA to HDMI), but you will get quite a cable constellation. 
That will probably work, but maybe a real crash cart solution with VGA like the CV211 is more suitable for you? 

Cheers

**Comment by sipper69** [comment]
Interesting!

Well, Control3 should work with any video capture device.

If you have a cable which captures your VGA and delivers it to your PC, you can use it.

You can still use any low-budget HDMI capture device with a converter (VGA to HDMI), but you will get quite a cable constellation.
That will probably work, but maybe a real crash cart solution with VGA like the CV211 is more suitable for you?

Cheers

**Comment by sipper69** [comment]
This product directly captures VGA, worth trying. Latency is important though, when it's too high, the responsiveness of the mouse is pretty frustrating. 

https://a.aliexpress.com/_EJo2Esf

**Comment by sipper69** [comment]
Tested the adapter.
Works really great!!
